### ISSUE TITLE
Failed to compile. Building from source

### ISSUE THREAD

**Issue by bhaswata08** [FlowTestAI/FlowTest#91]
```bash
[bhaswata08@archlinux FlowTest-main]$ pnpm start

> flowtest@1.0.0 start /home/bhaswata08/Downloads/FlowTest-main
> pnpm run build && cd packages/flowtest-electron && pnpm start


> flowtest@1.0.0 build /home/bhaswata08/Downloads/FlowTest-main
> react-scripts build

Creating an optimized production build...

🌼   daisyUI 4.10.2
├─ ✔︎ 1 theme added              https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:   https://opencollective.com/daisyui

Failed to compile.

Module not found: Error: Can't resolve './compute/complexnode' in '/home/bhaswata08/Downloads/FlowTest-main/src/components/molecules/flow/graph'


 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

System specs: 
OS: Arch Linux x86_64
Kernel: 6.8.7-arch1-2
CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q

**Comment by jsajal** [comment]
@bhaswata08 thank for reporting this.

I quickly tried to reproduce locally but i am not able to reproduce the error you are getting. 

I am running it on mac M1. Let's get on a call maybe and I can guide you step by step. Let me know when you are available

<img width="1642" alt="Screenshot 2024-05-02 at 12 30 43 AM" src="https://github.com/FlowTestAI/FlowTest/assets/5829490/183cfb3b-0563-4b44-bede-3eb06b621ee4">

**Comment by jsajal** [comment]
Feel free to share a recording of a fresh clone and setup. That would be super helpful for me to debug the problem

**Comment by bhaswata08** [comment]
[Screencast_20240503_115902.webm](https://github.com/FlowTestAI/FlowTest/assets/106006087/b198a944-0a3b-4c14-9f8e-e155eeb78173)

**Comment by bhaswata08** [comment]
> @bhaswata08 thank you for reporting this.
> 
> I quickly tried to reproduce locally but i am not able to reproduce the error you are getting.
> 
> I am running it on mac M1. Let's get on a call maybe and I can guide you step by step. Let me know when you are available
> <img alt="Screenshot 2024-05-02 at 12 30 43 AM" width="1642" src="https://private-user-images.githubusercontent.com/5829490/327348108-183cfb3b-0563-4b44-bede-3eb06b621ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MTgyNzMsIm5iZiI6MTcxNDcxNzk3MywicGF0aCI6Ii81ODI5NDkwLzMyNzM0ODEwOC0xODNjZmIzYi0wNTYzLTRiNDQtYmVkZS0zZWIwNmI2MjFlZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMDYzMjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODMwODk4ZjA5OThlYzMwOTk1YTU0Mzc2MmExYzVkNWU3NmNhYzI5N2MzMDZjOTU2MmRhOWViYmM1NTRhZmQzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eWRnKsJL1gX_G1aBsZF1S2BtgOiE77c3Gzifqpl9_pc">

Sure If we can figure it out, I will be available in between 11PM - 2PM IST or 8PM-10PM IST

**Comment by xelacast** [comment]
@bhaswata08 try this and see if it works. Make these changes in your locally cloned repository and then run ```pnpm start``` again

in the src/molecules/flow/graph/Graph.js file
Change this import filepath ```'import complexNode from './compute/requestNode'``` to this 

```javascript
import complexNode from './compute/complexnode';
```

Then in src/molecules/flow/graph/compute
Change the filename of 'complexNode.js' to 'complexnode.js'. (I lower cased the N)
```
complexnode.js
```

I'm going to put in a PR to change the file names and paths.

**Comment by jsajal** [comment]
@xelacast good spot with the file name, i think the import itself is correct https://github.com/FlowTestAI/FlowTest/blob/main/src/components/molecules/flow/graph/Graph.js#L7 
`import complexNode from './compute/complexnode'

just the file name needs to change from 'complexNode.js' to 'complexnode.js'.

i wonder why when you (during your pnpm pr) and i complie it locally, it doesn't give any errror

**Comment by jsajal** [comment]
oh i see there is this import also missplled 

```import requestNode from './compute/requestNode';``` should be

```import requestNode from './compute/requestnode';```

I wonder why my local doesn't give that error? 🤔

**Comment by xelacast** [comment]
@jsajal Im not sure. I was thinking it might have to do with the Apple chips but I have no clue otherwise. I have a typescript extension that was able to pick up the error or I probably wouldn't have noticed it as soon as I did.

**Comment by jsajal** [comment]
> @jsajal Im not sure. I was thinking it might have to do with the Apple chips but I have no clue otherwise. I have a typescript extension that was able to pick up the error or I probably wouldn't have noticed it as soon as I did.

oh, wow what is the extension that you are using?

**Comment by jsajal** [comment]
@bhaswata08 i just merged the fix, you can get the latest main, it should work now

**Comment by bhaswata08** [comment]
Ok I have tested it out now, It launches successfully. Thanks for the support!

**Comment by jsajal** [comment]
Great, detailed docs are presented here on how to get started https://flowtestai.gitbook.io/flowtestai/installation/getting-started

 let us know for more feedbacks.
